### ISSUE TITLE
is this the best lib for the task?

### ISSUE THREAD

**Issue by ORESoftware** [piscium2010/react-proptypes-to-typescript#9]
is this the best lib for the task? looking for a good way to:

generate TS definitions from propTypes or the other way around.

doing it this way is probably best:

```typescript
Comp.propTypes = { ...s }

type Def = mapper(Comp.propTypes);
```

is that right?

**Comment by piscium2010** [comment]
i think u are trying to generate TS definitions and do not intend to remove propTypes. If i am right, then this is not the "best" lib for you.

This lib is for migration, it may not fit your need

**Comment by piscium2010** [comment]
> is this the best lib for the task? looking for a good way to:
> 
> generate TS definitions from propTypes or the other way around.
> 
> doing it this way is probably best:
> 
> ```ts
> Comp.propTypes = { ...s }
> 
> type Def = mapper(Comp.propTypes);
> ```
> 
> is that right?

i think u are trying to generate TS definitions but do not intend to remove propTypes. If i am right, then this is not the "best" lib for you.

This lib is for migration, it may not fit your need.

Personally i don't suggest keep both of them, just use one and use it in a clean way.

By the way, thanks for your start
